"""
fuzzy tests measure if CER values remain below threshold
NOTE: undiacritized text is expected to have high failure

gold:
    CER: 4.022988505747127 WER: 18.75
    Espeak CER: 19.612068965517242 Espeak WER: 60.57692307692307

open-dict-data:
    OpenDictData (unambiguous word) CER: 37.96140644893748
    OpenDictData (ambiguous word) CER: 44.03312019686548

open-dict-data + tashkeel:
    OpenDictData (unambiguous word) CER: 17.305294014288226
    OpenDictData (ambiguous word) CER: 25.898605894068115

neurlang:
    Neurlang CER: 43.02198469573667

neurlang + tashkeel:
    Neurlang CER: 36.76167726088775
"""
import os.path
import random
import string
from typing import List, Dict

import jiwer
import pytest
from arbtok.espeak_wrapper import EspeakPhonemizer
from arbtok.tashkeel import TashkeelDiacritizer

from arbtok.tokenizer import Sentence, PUNCT
from tests.test_ipa import ALL_TEST_CASES

# maximum allowed error rate in gold set
# test that accuracy doesn't go down over time
MAX_GOLD_CER = 5
MAX_GOLD_WER = 20
DEBUG = False  # set to True to enable failing tests for visual inspection


def test_gold_cer():
    total_chars = 0
    total_char_errors = 0
    total_words = 0
    total_word_errors = 0

    for text, expected, _ in ALL_TEST_CASES:
        result = Sentence(text).ipa

        expected = expected.strip()
        cer = jiwer.cer(expected, result) * 100
        wer = jiwer.wer(expected, result) * 100

        total_char_errors += cer * len(expected) / 100
        total_chars += len(expected)
        total_word_errors += wer * len(expected.split()) / 100
        total_words += len(expected.split())

    overall_cer = (total_char_errors / total_chars) * 100 if total_chars > 0 else 0
    overall_wer = (total_word_errors / total_words) * 100 if total_words > 0 else 0
    print("\n", "CER:", overall_cer, "WER:", overall_wer)
    assert overall_cer <= MAX_GOLD_CER
    assert overall_wer <= MAX_GOLD_WER


def test_better_than_espeak():
    total_chars = 0
    total_char_errors = 0
    total_char_errors_espk = 0
    total_words = 0
    total_word_errors = 0
    total_word_errors_espk = 0

    espeak = EspeakPhonemizer()

    for text, expected, _ in ALL_TEST_CASES:
        # NOTE: drop IPA stress marks, not present in ground_truth
        result_espk = espeak.phonemize_string(text, "ar"). \
            replace(".", ""). \
            replace("ˈ", ""). \
            replace("ˌ", "")
        result = Sentence(text).ipa

        expected = expected.strip()
        cer = jiwer.cer(expected, result) * 100
        wer = jiwer.wer(expected, result) * 100
        cer_espk = jiwer.cer(expected, result_espk) * 100
        wer_espk = jiwer.wer(expected, result_espk) * 100

        total_char_errors += cer * len(expected) / 100
        total_char_errors_espk += cer_espk * len(expected) / 100
        total_chars += len(expected)
        total_word_errors += wer * len(expected.split()) / 100
        total_word_errors_espk += wer_espk * len(expected.split()) / 100
        total_words += len(expected.split())

    overall_cer = (total_char_errors / total_chars) * 100 if total_chars > 0 else 0
    overall_wer = (total_word_errors / total_words) * 100 if total_words > 0 else 0
    overall_cer_espk = (total_char_errors_espk / total_chars) * 100 if total_chars > 0 else 0
    overall_wer_espk = (total_word_errors_espk / total_words) * 100 if total_words > 0 else 0

    print("\n", "CER:", overall_cer, "WER:", overall_wer)
    print("\n", "Espeak CER:", overall_cer_espk, "Espeak WER:", overall_wer_espk)
    # Not worse than espeak
    assert overall_cer <= overall_cer_espk
    assert overall_wer <= overall_wer_espk


# NOTE: tests below will have high failure rate due to libtashkeel usage
#  this tokenizer was meant to handle fully diacritized text
tashkeel = TashkeelDiacritizer()

# TODO - is this lexicon accurate?
# undiacritized-to-ipa dataset from https://github.com/open-dict-data/ipa-dict
# Arabic IPA has been generated by Tim Buckwalter's Arabic Morphological Analyzer with adjustments to allow for UTF-8 input and IPA output
# https://catalog.ldc.upenn.edu/LDC2004L02
# with inspiration from the arabic_tools project by @lingz.
# https://github.com/lingz/arabic_tools
MAX_OPENDICT_AMBIGUOUS_CER = 30  # multiple transcriptions in test set
MAX_OPENDICT_UNAMBIGUOUS_CER = 20  # single transcription in test set
N_WORDS = 50000  # dataset is huge, test random N words

with open(f"{os.path.dirname(__file__)}/ar_test.txt") as f:
    WORD_DICT: Dict[str, List[str]] = {
        l.split("\t")[0]: l.split("\t")[1].split(", ")
        for l in set(f.read().split("\n")) if "\t" in l
    }
    UNAMBIGUOUS_WORDS: List[str] = [
        w for w, ipa in WORD_DICT.items()
        if len(ipa) == 1
    ]
    AMBIGUOUS_WORDS: List[str] = [
        w
        for w, ipa in WORD_DICT.items()
        if len(ipa) > 1
    ]

    UNAMBIGUOUS_TESTS = [
        (word, WORD_DICT[word][0].strip("/ "), "unambiguous undiacritized word")
        for word in UNAMBIGUOUS_WORDS
    ]
    print("\nN unambiguous tests", len(UNAMBIGUOUS_TESTS))
    random.shuffle(UNAMBIGUOUS_TESTS)

    # consider every transcription
    AMBIGUOUS_TESTS = [
        (word, ipa.strip("/ "), "ambiguous undiacritized word")
        for word in AMBIGUOUS_WORDS
        for ipa in WORD_DICT[word]
    ]
    print("\nN ambiguous tests", len(AMBIGUOUS_TESTS))
    random.shuffle(AMBIGUOUS_TESTS)


def test_max_tashkeel_errors_ambiguous():
    total_chars = 0
    total_char_errors = 0

    for text, expected, _ in AMBIGUOUS_TESTS[:N_WORDS]:
        diacritized = tashkeel.diacritize(text, 0.8)
        result = Sentence(diacritized).ipa

        expected = expected.strip()

        cer = jiwer.cer(expected, result) * 100

        total_char_errors += cer * len(expected) / 100
        total_chars += len(expected)

    overall_cer = (total_char_errors / total_chars) * 100 if total_chars > 0 else 0
    print("\n", "Tashkeel (ambiguous word) CER:", overall_cer)
    assert overall_cer <= MAX_OPENDICT_AMBIGUOUS_CER


def test_max_tashkeel_errors_unambiguous():
    total_chars = 0
    total_char_errors = 0

    for text, expected, _ in UNAMBIGUOUS_TESTS[:N_WORDS]:
        diacritized = tashkeel.diacritize(text, 0.8)
        result = Sentence(diacritized).ipa

        expected = expected.strip()

        cer = jiwer.cer(expected, result) * 100

        total_char_errors += cer * len(expected) / 100
        total_chars += len(expected)

    overall_cer = (total_char_errors / total_chars) * 100 if total_chars > 0 else 0
    print("\n", "Tashkeel (unambiguous word) CER:", overall_cer)
    assert overall_cer <= MAX_OPENDICT_AMBIGUOUS_CER


# mainly for visual inspection - most will fail
@pytest.mark.parametrize("arabic_text, expected_ipa, description", UNAMBIGUOUS_TESTS[:500])
def test_undiacritized_ipa(arabic_text, expected_ipa, description):
    if not DEBUG:
        return
    diacritized = tashkeel.diacritize(arabic_text, 0.8)
    result = Sentence(diacritized).ipa.strip(PUNCT + string.whitespace)
    expected = expected_ipa.strip(PUNCT + string.whitespace)
    assert result == expected, f"Failed {description}: Input '{arabic_text}'"


# mainly for visual inspection - most will fail
@pytest.mark.parametrize("arabic_text, expected_ipa, description", AMBIGUOUS_TESTS[:500])
def test_undiacritized_ipa_ambiguous(arabic_text, expected_ipa, description):
    if not DEBUG:
        return
    diacritized = tashkeel.diacritize(arabic_text, 0.8)
    result = Sentence(diacritized).ipa.strip(PUNCT + string.whitespace)
    expected = expected_ipa.strip(PUNCT + string.whitespace)
    assert result == expected, f"Failed {description}: Input '{arabic_text}'"


# TODO - is this lexicon accurate?
# https://github.com/neurlang/dataset/tree/master/arabic
MAX_NEURLANG_CER = 40  # single transcription in test set

with open(f"{os.path.dirname(__file__)}/lexicon.tsv") as f:
    WORD_DICT: Dict[str, str] = {
        l.split("\t")[0]: l.split("\t")[1]
        for l in f.read().split("\n") if "\t" in l
    }
    LEXICON_TESTS = [
        (word, ipa, "lexicon word")
        for word, ipa in WORD_DICT.items()
    ]
    print("\nN lexicon tests", len(LEXICON_TESTS))
    random.shuffle(LEXICON_TESTS)


def test_max_lexicon_errors():
    total_chars = 0
    total_char_errors = 0

    for text, expected, _ in LEXICON_TESTS:
        diacritized = tashkeel.diacritize(text, 0.8)
        result = Sentence(diacritized).ipa
        expected = expected.strip()

        cer = jiwer.cer(expected, result) * 100

        total_char_errors += cer * len(expected) / 100
        total_chars += len(expected)

    overall_cer = (total_char_errors / total_chars) * 100 if total_chars > 0 else 0
    print("\n", "Neurlang CER:", overall_cer)
    assert overall_cer <= MAX_NEURLANG_CER
