"""Dialect gold sets for the regional reflex cascade.

Model-generated by reasoning from documented zone reflexes, pending
native-speaker validation — the same honesty stance the rest of the
repo's gold data carries. Every item below records its derivation: the
MSA rule-cascade form on the left of the arrow, the zone reflexes
applied, and the target IPA on the right. Where a form was uncertain a
different, surer word was chosen instead.

The reflexes the cascade applies per zone (see
``arbtok.dialects.DIALECT_CONSONANT_OVERRIDES``):

- EGYPTIAN  : ق→ʔ, ج→g, ث→t, ذ→d, ظ→dˤ
- LEVANTINE : ق→ʔ, ج→ʒ, ث→t, ذ→d, ظ→dˤ          (urban defaults)
- GULF      : ق→g, ج→j, interdentals retained (θ ð ðˤ)
- MAGHREBI  : ق→q (kept), ج→ʒ, ث→t, ذ→d, ظ→dˤ, + schwa reduction

Each tuple is ``(arabic, expected_ipa, dialect, reasoning)``.
"""
from arbtok.dialects import ArabicDialect

# === EGYPTIAN (Cairene) ===
# Signature: qāf → glottal stop, jīm → hard /g/, interdentals → stops.
EGYPTIAN_TESTS = [
    ("قَلْب", "ʔalb", ArabicDialect.EGYPTIAN,
     "MSA qalb; ق→ʔ → ʔalb (heart)."),
    ("قَلَم", "ʔalam", ArabicDialect.EGYPTIAN,
     "MSA qalam; ق→ʔ → ʔalam (pen)."),
    ("قَمَر", "ʔamar", ArabicDialect.EGYPTIAN,
     "MSA qamar; ق→ʔ → ʔamar (moon)."),
    ("قَلِيل", "ʔaliːl", ArabicDialect.EGYPTIAN,
     "MSA qaliːl; ق→ʔ → ʔaliːl (few)."),
    ("جَمِيل", "gamiːl", ArabicDialect.EGYPTIAN,
     "MSA dʒamiːl; ج→g → gamiːl (beautiful) — the canonical Cairo gīm."),
    ("جَبَل", "gabal", ArabicDialect.EGYPTIAN,
     "MSA dʒabal; ج→g → gabal (mountain)."),
    ("جَدِيد", "gadiːd", ArabicDialect.EGYPTIAN,
     "MSA dʒadiːd; ج→g → gadiːd (new)."),
    ("جُبْن", "gubn", ArabicDialect.EGYPTIAN,
     "MSA dʒubn; ج→g → gubn (cheese)."),
    ("ثَوْب", "tawb", ArabicDialect.EGYPTIAN,
     "MSA θawb; ث→t → tawb (garment). aw diphthong retained."),
    ("ثَلَاثَة", "talaːta", ArabicDialect.EGYPTIAN,
     "MSA θalaːθa; both ث→t → talaːta (three)."),
    ("ذَهَب", "dahab", ArabicDialect.EGYPTIAN,
     "MSA ðahab; ذ→d → dahab (gold)."),
    ("ظُهْر", "dˤuhr", ArabicDialect.EGYPTIAN,
     "MSA ðˤuhr; inherited Cairene ظ→dˤ (merges with ض, matching ث→t/ذ→d) "
     "→ dˤuhr (noon). The zˤ reflex is the borrowed/literary one."),
    ("قَلْب جَمِيل", "ʔalb gamiːl", ArabicDialect.EGYPTIAN,
     "Phrase: ق→ʔ and ج→g across two words → ʔalb gamiːl (beautiful heart)."),
]

# === LEVANTINE (urban Damascus/Beirut) ===
# Signature: qāf → glottal stop, jīm → ʒ, interdentals → dental stops.
LEVANTINE_TESTS = [
    ("قَلْب", "ʔalb", ArabicDialect.LEVANTINE,
     "MSA qalb; ق→ʔ → ʔalb (heart)."),
    ("قَمَر", "ʔamar", ArabicDialect.LEVANTINE,
     "MSA qamar; ق→ʔ → ʔamar (moon)."),
    ("قَرِيب", "ʔariːb", ArabicDialect.LEVANTINE,
     "MSA qariːb; ق→ʔ → ʔariːb (near)."),
    ("قَلِيل", "ʔaliːl", ArabicDialect.LEVANTINE,
     "MSA qaliːl; ق→ʔ → ʔaliːl (few)."),
    ("جَمِيل", "ʒamiːl", ArabicDialect.LEVANTINE,
     "MSA dʒamiːl; ج→ʒ → ʒamiːl (beautiful) — Levantine fricative jīm."),
    ("جَبَل", "ʒabal", ArabicDialect.LEVANTINE,
     "MSA dʒabal; ج→ʒ → ʒabal (mountain)."),
    ("جَدِيد", "ʒadiːd", ArabicDialect.LEVANTINE,
     "MSA dʒadiːd; ج→ʒ → ʒadiːd (new)."),
    ("جُبْن", "ʒubn", ArabicDialect.LEVANTINE,
     "MSA dʒubn; ج→ʒ → ʒubn (cheese)."),
    ("ثَوْب", "tawb", ArabicDialect.LEVANTINE,
     "MSA θawb; urban ث→t → tawb (garment)."),
    ("ثَلَاثَة", "talaːta", ArabicDialect.LEVANTINE,
     "MSA θalaːθa; urban ث→t (both) → talaːta (three)."),
    ("ذَهَب", "dahab", ArabicDialect.LEVANTINE,
     "MSA ðahab; urban ذ→d → dahab (gold)."),
    ("ظُهْر", "dˤuhr", ArabicDialect.LEVANTINE,
     "MSA ðˤuhr; ظ→dˤ (emphatic stop, matching the ذ→d merger) → dˤuhr (noon)."),
    ("قَلْب جَمِيل", "ʔalb ʒamiːl", ArabicDialect.LEVANTINE,
     "Phrase: ق→ʔ and ج→ʒ → ʔalb ʒamiːl (beautiful heart)."),
]

# === GULF (Gulf proper) ===
# Signature: qāf → /g/, jīm → palatal /j/, interdentals RETAINED.
GULF_TESTS = [
    ("قَلْب", "galb", ArabicDialect.GULF,
     "MSA qalb; ق→g → galb (heart) — the Gulf voiced qāf."),
    ("قَلَم", "galam", ArabicDialect.GULF,
     "MSA qalam; ق→g → galam (pen)."),
    ("قَمَر", "gamar", ArabicDialect.GULF,
     "MSA qamar; ق→g → gamar (moon)."),
    ("قَرِيب", "gariːb", ArabicDialect.GULF,
     "MSA qariːb; ق→g → gariːb (near)."),
    ("جَمِيل", "jamiːl", ArabicDialect.GULF,
     "MSA dʒamiːl; Gulf-proper ج→j (yodization) → jamiːl (beautiful)."),
    ("جَبَل", "jabal", ArabicDialect.GULF,
     "MSA dʒabal; ج→j → jabal (mountain)."),
    ("جَدِيد", "jadiːd", ArabicDialect.GULF,
     "MSA dʒadiːd; ج→j → jadiːd (new)."),
    ("ثَوْب", "θawb", ArabicDialect.GULF,
     "MSA θawb; interdental ث RETAINED → θawb (garment)."),
    ("ثَلَاثَة", "θalaːθa", ArabicDialect.GULF,
     "MSA θalaːθa; both ث RETAINED → θalaːθa (three)."),
    ("ذَهَب", "ðahab", ArabicDialect.GULF,
     "MSA ðahab; interdental ذ RETAINED → ðahab (gold)."),
    ("ظُهْر", "ðˤuhr", ArabicDialect.GULF,
     "MSA ðˤuhr; emphatic interdental ظ RETAINED → ðˤuhr (noon)."),
    ("بَقَرَة", "bagara", ArabicDialect.GULF,
     "MSA baqara; ق→g → bagara (cow). No interdentals, no reduction."),
    ("قَلْب جَمِيل", "galb jamiːl", ArabicDialect.GULF,
     "Phrase: ق→g and ج→j → galb jamiːl (beautiful heart)."),
]

# === MAGHREBI (North-African defaults) ===
# Signature: qāf kept /q/, jīm → ʒ, interdentals merged to stops,
# + conservative schwa reduction in open non-final medial syllables.
MAGHREBI_TESTS = [
    ("قَلْب", "qalb", ArabicDialect.MAGHREBI,
     "MSA qalb; ق kept as q (conservative default; g also occurs) → qalb (heart)."),
    ("قَلَم", "qalam", ArabicDialect.MAGHREBI,
     "MSA qalam; ق kept; final/closed syllables unreduced → qalam (pen)."),
    ("قَمَر", "qamar", ArabicDialect.MAGHREBI,
     "MSA qamar; ق kept; closed final, no reduction → qamar (moon)."),
    ("جَمِيل", "ʒamiːl", ArabicDialect.MAGHREBI,
     "MSA dʒamiːl; ج→ʒ → ʒamiːl (beautiful)."),
    ("جَبَل", "ʒabal", ArabicDialect.MAGHREBI,
     "MSA dʒabal; ج→ʒ → ʒabal (mountain)."),
    ("جَدِيد", "ʒadiːd", ArabicDialect.MAGHREBI,
     "MSA dʒadiːd; ج→ʒ → ʒadiːd (new)."),
    ("ثَوْب", "tawb", ArabicDialect.MAGHREBI,
     "MSA θawb; interdental merger ث→t → tawb (garment)."),
    ("ثَلَاثَة", "talaːta", ArabicDialect.MAGHREBI,
     "MSA θalaːθa; ث→t (both); long aː blocks reduction → talaːta (three)."),
    ("ذَهَب", "dahab", ArabicDialect.MAGHREBI,
     "MSA ðahab; merger ذ→d → dahab (gold)."),
    ("ظُهْر", "dˤuhr", ArabicDialect.MAGHREBI,
     "MSA ðˤuhr; ظ→dˤ (emphatic stop merger) → dˤuhr (noon)."),
    ("بَقَرَة", "baqəra", ArabicDialect.MAGHREBI,
     "MSA baqara; ق kept; medial short a in open non-final syllable → ə "
     "(approximation) → baqəra (cow)."),
    ("كَتَبَ", "katəba", ArabicDialect.MAGHREBI,
     "MSA kataba; medial open-syllable a → ə (approximation) → katəba (he wrote)."),
    ("قَلْب جَمِيل", "qalb ʒamiːl", ArabicDialect.MAGHREBI,
     "Phrase: ق kept, ج→ʒ → qalb ʒamiːl (beautiful heart)."),
]

# All dialect gold items, flattened for parametrization.
ALL_DIALECT_TESTS = (
    EGYPTIAN_TESTS + LEVANTINE_TESTS + GULF_TESTS + MAGHREBI_TESTS
)
